FROM node:16.14-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY ./package*.json .
COPY ./tsconfig*.json .
COPY ./build ./.next

RUN npm ci -f --only=production 

EXPOSE 8080

CMD ["npm","run","start"]
