FROM node:16.14-alpine as build

WORKDIR /

COPY package*.json ./
COPY .env ./

RUN npm ci -f

COPY . .
RUN npm run build


FROM node:16.14-alpine

WORKDIR /

ENV NODE_ENV=production

# COPY --from=build /app/dist/apps/webapp/package*.json ./
COPY --from=build /package*.json ./
COPY --from=build /dist ./dist

RUN npm ci -f --only=production --ignore-scripts

EXPOSE 8080

CMD ["npm","run","start"]
