export const strings = {
  YOUR_ARE_NOT_AUTHORIZED: "You are not authorized!",
  YOU_DONT_HAVE_PERMISSIONS_MESSAGE:
    "You do not have permission to view this page using the credentials that you have provided while login.",
  CONTACT_SITE_ADMIN: "Please contact your site administrator.",
  BACK_TO_HOME: "Back to Home",
  PAGE_NOT_FOUND: "Page Not Found",
  REQUESTED_URL_NOT_FOUND:
    "Oops! 😖 The requested URL was not found on this server.",
  OOPS_SOMETHING_WENT_WRONG: "Oops, something went wrong!",
  INTERNAL_SERVER_ERROR_CONTACT_ADMIN:
    "There was an error with the internal server. Please contact your site administrator.",
  ACCEPT_PRIVACY_POLICY_TERMS: "You must accept the privacy policy & terms",
  SIGN_UP: "Sign up",
  ALREADY_HAVE_ACCOUNT: "Already have an account?",
  SIGN_IN_INSTEAD: "Sign in instead",
  EMAIL_PASSWORD_INVALID: "Email or Password is invalid",
  FORGOT_PASSWORD: "Forgot Password?",
  LOGIN: "Login",
  PASSWORD: "Password",
  NEW_TO_PLATFORM: "New on our platform?",
  CREATE_ACCOUNT: "Create an account",
  WELLCOME_TO: "Welcome to",
  STATUS_MESSAGE_TEMPORARILY_DONE:
    "You are temporarily done; please come back later to review more words.",
  STATUS_MESSAGE_PERMANENTLY_DONE:
    "You have no more words to review, you are permanently done.",
  STATUS_MESSAGE_ADD_WORDS: "Please add few words to review.",
  TOAST_MESSAGE_WORD_ADDED_SUCCESS: "Word added successfully",
  TOAST_MESSAGE_WORD_ADDED_FAIL: "Failed to add the word",
  TOAST_MESSAGE_WORD_EDITED_SUCCESS: "Word edited successfully",
  TOAST_MESSAGE_WORD_EDITED_FAIL: "Failed to edit the word",
  TOAST_MESSAGE_WORD_DELETED_SUCCESS: "Word deleted successfully",
  TOAST_MESSAGE_WORD_DELETED_FAIL: "Failed to delete the word",
  TITLE_ADD_NEW_WORD: "Adding New Word",
  TITLE_EDIT_NEW_WORD: "Edit Word",
  BUTTON_ADD: "Add",
  BUTTON_EDIT: "Edit",
  ADD_WORD: "Add Word",
  EDIT_WORD: "Edit Word",
  LABEL_WORD: "Word",
  LABEL_DESCRIPTIONS: "Description",
  PLACEHOLDER_WORD: "Abject",
  PLACEHOLDER_DESCRIPTION: "Of the most contemptible kind",
  HELPER_TEXT_WORD: "A difficult word you want to review",
  HELPER_TEXT_DESCRIPTION: "Meaning or description of the above word",
  FLASHCARD_WORD: "Word",
  FLASHCARD_DESCRIPTION: "Description",
  FLASHCARD_BIN_NUMBER: "Bin Number",
  FLASHCARD_TIME_TO_NEXT_APPEARENCE: "Time To Next Appearance",
  FLASHCARD_WRONG_COUNT: "No of Times Answered Incorrect",
  BUTTON_DELETE: "Delete",
  ARE_YOU_SURE: " Are you sure?",
  BUTTON_YES: "Yes",
  BUTTON_NO: "No",
};
